### ISSUE TITLE
not working i a getting this error plzz reply

### ISSUE THREAD

**Issue by naashit10** [ProgrammingHero1/audiobook#1]
item 1 in _argtypes_ passes a union by value, which is unsupported.

**Comment by CosmicalTroll** [comment]
me too same problem

**Comment by shravanasati** [comment]
Which version of python are pyttsx3  are you using?

**Comment by ashraf-minhaj** [comment]
> item 1 in _argtypes_ passes a union by value, which is unsupported.

This error depends on python version. The libraries that read and process the pdf file needs to support the python version. I recommend using one version lower than the latest python version. 
Like, if we have now python3.8.5 then use python 3.8.4
Reason? Not every library is managed properly, so they are not updates as fast as python version update.
