### ISSUE TITLE
Does not read the whole pages

### ISSUE THREAD

**Issue by Premjit0** [ProgrammingHero1/audiobook#15]
sir it only read the http links and chapter number and page number only...

**Comment by shravanasati** [comment]
For reading all pages of a PDF, you need to run a for loop to extract text from every page and then make the program speak the whole text. If you want to create an audio file (mp3) which contains audio for every single page of the PDF, checkout my repository: https://github.com/Shravan-1908/Audiobook-Maker

**Comment by ashraf-minhaj** [comment]
> sir it only read the http links and chapter number and page number only...

The thing is that the library can only read printable texts. If the texts are not in printable format, it can't read them. To extract text from non-printable format such as images we need to perform some kind of image operations.

**Comment by shravanasati** [comment]
@ashraf-minhaj is right, ```PyPDF2``` can only read printable texts. To read, text from image, you'll need an **OCR**. This article might help you: https://towardsdatascience.com/how-to-extract-text-from-images-with-python-db9b87fe432b
