### ISSUE TITLE
I get this error and would like some help if possible.

### ISSUE THREAD

**Issue by CosmicalTroll** [ProgrammingHero1/audiobook#2]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

**Comment by harshraj6982** [comment]
Duplicate of #1 
Please close this issue.

**Comment by CosmicalTroll** [comment]
> Duplicate of #1 
> Please close this issue. 

I do not understand, can u please be more specific?(I'm a beginner)

**Comment by harshraj6982** [comment]
Press the close issue button that will close this issue.

**Comment by CosmicalTroll** [comment]
> Press the close issue button that will close this issue.

I am talking about the error not the issue

**Comment by harshraj6982** [comment]
The error you faced and the issue you raised regarding that is already created by someone before, you can see this in the issue section. So that I am saying that please close this issue and wait for author or anybody who can fix the error.

**Comment by shravanasati** [comment]
Which versions of python, pyttsx3 and pypdf2 are you using?

**Comment by ashraf-minhaj** [comment]
See the [answer of this issue](https://github.com/ProgrammingHero1/audiobook/issues/1).
