### ISSUE TITLE
Fails to read first 7 pages

### ISSUE THREAD

**Issue by jeevanholla** [ProgrammingHero1/audiobook#4]
Because of this hardcoded value of 7, "for num in range(7, pages):", this code will fail to read document less than 7 pages or skip first 7 pages of larger document. It was meant to skip content section, so it would have been to make it command line argument for user to choose from.

**Comment by ashraf-minhaj** [comment]
It will not fail actually, it's how it is coded. Just change the value from 7 to whatever you like. It can and will read the pages.

**Comment by naveenramcg** [comment]
> Because of this hardcoded value of 7, "for num in range(7, pages):", this code will fail to read document less than 7 pages or skip first 7 pages of larger document. It was meant to skip content section, so it would have been to make it command line argument for user to choose from.

The code is programmed to skip the first 7 pages. You can use any number to make the code suit your need instead of seven. To read the whole pages, you can use code:  "for num in range(pages):". This helps you read the full pdf.
