### ISSUE TITLE
Same unsolvable error always

### ISSUE THREAD

**Issue by anapeksha** [ProgrammingHero1/audiobook#9]
code 139 (interrupted by signal 11: SIGSEGV) error returned always
![Screenshot from 2020-10-02 16-40-57](https://user-images.githubusercontent.com/46746006/94917520-4efe6100-04ce-11eb-8595-7ec2b28190c6.png)

**Comment by shravanasati** [comment]
Don't open the `book`. Just pass the `book` string directly to the ```PdfFileReader``` class. The class ```PdfFileReader``` takes the path of the PDF file (string), not a binary file.

**Comment by ashraf-minhaj** [comment]
You opened the file in read-binary format. 
open('file_name", 'r') should work just as fine.
